"""Offline RL end to end: logs in, a validated policy out.

    python examples/offline_rl.py

The workflow this mirrors is the one most applied projects actually face:

1. an incumbent controller runs in production and its decisions are logged;
2. a candidate policy is fitted **offline** from those logs -- the real system
   is never exposed to an untested policy;
3. the candidate is scored **off-policy**, from the same logs, before anyone
   considers deploying it;
4. only then is the on-policy value measured, here to show that the off-policy
   estimate was honest.

Step 3 is the one that gets skipped in practice, and the one that decides
whether the rollout is a promotion or an incident.
"""
import numpy as np

from rlkit.algorithms import BatchQLearning, OffPolicyMonteCarlo
from rlkit.buffers import ReplayBuffer
from rlkit.envs import GridWorld
from rlkit.evaluation import evaluate_policy, off_policy_evaluation

GAMMA = 0.95
EPISODES = 2000
MAX_STEPS = 30


def make_env():
    # The obstacle at (1,2) walls off the right-hand column, so the incumbent's
    # "along the top, then down" route dead-ends and it only ever reaches the
    # goal by accident. Its logs are exactly the kind you inherit in practice:
    # plentiful, biased, and generated by a policy nobody would defend.
    return GridWorld(rows=3, cols=3, start=(0, 0), goals=((2, 2),),
                     obstacles=((1, 2),), step_reward=-1.0, max_steps=MAX_STEPS)


def run_incumbent(env, incumbent, epsilon, episodes, seed):
    """Log episodes from an epsilon-greedy incumbent, keeping its probabilities.

    Both artefacts matter: the transition buffer feeds fitted-Q, and the
    per-action probabilities are what make off-policy evaluation possible at
    all. If your production logs do not record them, you cannot do step 3.
    """
    rng = np.random.default_rng(seed)
    buffer = ReplayBuffer(capacity=episodes * MAX_STEPS, seed=seed)
    dataset = []
    for _ in range(episodes):
        state = env.reset()
        episode = []
        for _ in range(MAX_STEPS):
            probs = np.full(env.n_actions, epsilon / env.n_actions)
            probs[incumbent[state]] += 1.0 - epsilon
            action = int(rng.choice(env.n_actions, p=probs))
            next_state, reward, done, info = env.step(action)
            truncated = bool(info.get("truncated", False))
            buffer.add(state, action, reward, next_state, done and not truncated)
            episode.append((state, action, reward, float(probs[action])))
            state = next_state
            if done:
                break
        dataset.append(episode)
    return buffer, dataset


def main():
    env = make_env()
    # "Go right along the top, then down the right edge" -- a rule that was
    # fine before someone put a machine at (1,2).
    incumbent = np.array([1, 1, 2,
                          1, 1, 2,
                          1, 1, 0])

    buffer, dataset = run_incumbent(env, incumbent, epsilon=0.4,
                                    episodes=EPISODES, seed=0)
    print(f"logged {len(dataset)} episodes / {len(buffer)} transitions "
          f"from the incumbent controller")

    fqi = BatchQLearning(env.n_states, env.n_actions, gamma=GAMMA)
    deltas = fqi.fit(buffer, iterations=500)
    print(f"fitted-Q converged in {len(deltas)} sweeps "
          f"(dataset coverage {fqi.coverage():.0%})")

    mc = OffPolicyMonteCarlo(env.n_states, env.n_actions, gamma=GAMMA,
                             init_value=-100.0)  # pessimistic: costs are negative
    mc.train_from_dataset(dataset, passes=3)

    # The logging policy itself is stochastic, so evaluate it as a probability
    # matrix: a deterministic target has to match every logged action in an
    # episode, and over a 30-step horizon that essentially never happens.
    behaviour_probs = np.full((env.n_states, env.n_actions), 0.4 / env.n_actions)
    behaviour_probs[np.arange(env.n_states), incumbent] += 0.6

    candidates = [
        ("incumbent (as logged)", behaviour_probs, incumbent),
        ("fitted-Q (in support)", *(2 * (fqi.greedy_policy(min_count=1),))),
        ("off-policy MC", *(2 * (mc.greedy_policy(),))),
    ]

    print(f"\n{'policy':<24} {'OPE (WIS)':>10} {'ESS':>8} {'overlap':>8}"
          f" {'true value':>11}")
    for name, ope_target, policy in candidates:
        ope = off_policy_evaluation(dataset, ope_target, gamma=GAMMA, method="wis")
        true = evaluate_policy(env, policy, episodes=200, max_steps=MAX_STEPS,
                               gamma=GAMMA)
        print(f"{name:<24} {ope['estimate']:10.2f} {ope['ess']:8.1f}"
              f" {ope['overlap']:8.1%} {true['mean_discounted_return']:11.2f}")

    print("\nTwo things to read off this table:")
    print("  * fitted-Q uses every logged transition, so it extracts a policy far")
    print("    better than the one that produced the data. Off-policy MC keeps only")
    print("    the suffixes its target policy agrees with, and on a log this biased")
    print("    that is too little signal -- batch methods win in practice for exactly")
    print("    this reason.")
    print("  * a low ESS or overlap means the log contains almost no evidence about")
    print("    that policy. The estimate is unproven, not good -- and a deterministic")
    print("    target over a long horizon is where importance sampling runs out of")
    print("    overlap first.")


if __name__ == "__main__":
    main()
